### ISSUE TITLE
Testovanie - dotazník

### ISSUE THREAD

**Issue by NorbertJu** [NorbertJu/ResolutionEditor#19]
1. Na aký účel ste editor použili?
- overenie riešenia, ktoré som predtým vypracoval na papieri
- vypracovanie celej úlohy
- nepoužil som ho
- iné (vlastná odpoveď)

2. Ako vám editor pomohol?
- našiel som si chybu
- overil som si riešenie
- lepšie som pochopil rezolvenciu a faktorizáciu
- lepšie som pochopil syntax zapisovania klauzúl a substitúcií
- nepomohol
- iné (vlastná odpoveď)

3. Ako intuitívne sa s editorom pracovalo?
1-5 bodov

4. Čo vám na editore chýbalo?
___ (vlastná odpoveď)

5. Odporučili by ste editor daľším študentom?
- áno
- možno
- nie

**Comment by NorbertJu** [comment]
@crnkjck Mohol by dotaznik vyzerat nejak takto? Co by prípadne trebalo zmenit?

https://docs.google.com/forms/d/e/1FAIpQLScO_m8K3_QKN5WRG3ss0NkEtbZBaBb4JNk5fceqngM2Ipf9ww/viewform

**Comment by crnkjck** [comment]
>     1. Na aký účel ste editor použili?
> 
>     * overenie riešenia, ktoré som predtým vypracoval na papieri
Možno „inak“ namiesto „na papieri“
>     * vypracovanie celej úlohy
>     * nepoužil som ho
>     * iné (vlastná odpoveď)
> 
>     1. Ako vám editor pomohol?
>     * našiel som si chybu
>     * overil som si riešenie
>     * lepšie som pochopil rezolvenciu a faktorizáciu
>     * lepšie som pochopil syntax zapisovania klauzúl a substitúcií
Tá syntax sa mi zdá zbytočná, ale možno by sa hodilo „lepšie som pochopil unifikáciu“.
>     * nepomohol
>     * iné (vlastná odpoveď)
> 
>     1. Ako intuitívne sa s editorom pracovalo?
>        1-5 bodov
> 
>     2. Čo vám na editore chýbalo?
>        ___ (vlastná odpoveď)
> 
>     3. Odporučili by ste editor daľším študentom?
**ď**a**l**ším
>     * áno
>     * možno
>     * nie

Ospravedlňujem sa, ale už si nespomínam, ako sme sa dohodli. Môžete mi pripomenúť, čo sme chceli robiť s dotazníkom? Chceli sme osloviť nejakých študentov na testovanie, či sme ho chceli proste rozposlať a dúfať, že dostaneme odpoveď? S kolegom Baluchom sme pri tomto druhom spôsobe žiaľ nemali veľký úspech…

**Comment by crnkjck** [comment]
Aha, este by sa hodilo do odpovedi pridat zensky rod: overil(a) som si riesenie… v 1. a 2. otazke. A este: nepomohol *mi*

Mam trocha problem s tym prekryvom medzi "overenie riešenia" v 1. otazke a "overil(a) som si riesenie" v 2. otazke. Mozno by bolo lepsie to nahradit v 2. otazke: "uistil(a) som sa o spravnosti svojho riesenia".

**Comment by crnkjck** [comment]
Este jedna vec: Piste odpovede ako cele vety s velkym pismenom na zaciatku a bodkou na konci.

**Comment by crnkjck** [comment]
Predsa este cosi – Napíšte do formulára krátky úvod: Kto ste, čo ste spravili, poproste respondenta o spoluprácu, vysvetlite, ako vám respondent pomôže, keď odpovie (spätná väzba, zlepšenie, posúdenie užitočnosti, objavenie problémov, … – vyberte a napíšte podľa seba).

K otázkam: Pridal by som možno aj pozitívnu otázku – Čo sa vám na editore páčilo? a negatívnu by som upravil na Čo sa vám na editore nepáčilo, chýbalo, čo by ste zmenili?

**Comment by NorbertJu** [comment]
Upravená verzia: https://docs.google.com/forms/d/e/1FAIpQLScO_m8K3_QKN5WRG3ss0NkEtbZBaBb4JNk5fceqngM2Ipf9ww/viewform
Vy ste spominali, ze na predmete Matematika 4 - Logika budete tento tyzden preberat/riesit rezolvenciu a studentom sa da aj rezolvencny editor s dotaznikom, takze plan bol asi rozposlat a dufat.

**Comment by crnkjck** [comment]
Myslim, ze dotaznik je fajn. Skusime to rozposlat a uvidime. Myslim, ze editor budu dost pouzivat, takze ked im za dotaznik slubime nejaky premiovy bod, tak si nan cas najdu.

S kolegom Baluchom bol problem hlavne v tom, ze velmi nepotrebovali pouzivat jeho novu funkcionalitu existujuceho nastroja, lebo si vystacili so starou, ktoru uz poznali.

Dobre, poslal by som to po cviceni. Ked editujete formular, v [Send] sa da vybrat Link a vygenerovat kratke URL na formular. Poslite mi ho, prosim.

**Comment by NorbertJu** [comment]
V poriadku, ďakujem.
https://forms.gle/nCJnsg8WTwjW1gxH7

**Comment by NorbertJu** [comment]
Este otazka, mam obmedzit odpovede na 1 s potrebou prihlasenia a zbierat emailove adresy, aby sme vedeli zistit, kto dotaznik vyplnil?

**Comment by crnkjck** [comment]
Pozrite si Skype, je tam ciastocne odpoved.
